routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('main',function (){
   return view('main.index');
});

Route::resource('about',\App\Http\Controllers\AboutController::class);

Route::resource('analysis',\App\Http\Controllers\AnalysisController::class);

Route::resource('call_me',\App\Http\Controllers\Call_meController::class);

Route::resource('contacts',\App\Http\Controllers\ContactsController::class);

Route::resource('customers',\App\Http\Controllers\CustomersController::class);

Route::resource('help_business',\App\Http\Controllers\Help_BusinessController::class);

Route::resource('home',\App\Http\Controllers\HomeController::class);

Route::resource('intro',\App\Http\Controllers\IntroController::class);

Route::resource('services',\App\Http\Controllers\ServicesController::class);

Route::resource('teams',\App\Http\Controllers\TeamsController::class);

app/Models/Call_me.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Call_me extends Model
{
    use HasFactory;
    protected $table='call_me';
    protected $fillable=['bold_text','top_text','option_1','option_2','option_3','name','phone','email','interested','chek_text'];
    public $timestamps=false;
}

app/Http/Controllers/Call_meController.php
<?php

namespace App\Http\Controllers;

use App\Models\Call_me;
use Illuminate\Http\Request;

class Call_meController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $call_me=Call_me::all();
        return view('admin.call_me.index',compact('call_me'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'bold_text'=>'required',
            'top_text'=>'required',
            'option_1'=>'required',
            'option_2'=>'required',
            'option_3'=>'required',
            'name'=>'required',
            'phone'=>'required',
            'email'=>'required',
            'interested'=>'required',
            'chek_text'=>'required'

        ]);

        Call_me::create([
            'bold_text'=>$request->bold_text,
            'top_text'=>$request->top_text,
            'option_1'=>$request->option_1,
            'option_2'=>$request->option_2,
            'option_3'=>$request->option_3,
            'name'=>$request->name,
            'phone'=>$request->phone,
            'email'=>$request->email,
            'interested'=>$request->interested,
            'chek_text'=>$request->chek_text


        ]);



        return redirect()->route('call_me.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Call_me $call_me)
    {
        $call_me->delete();
        return redirect()->route('call_me.index');
    }
}

resources/views/admin/call_me/index.blade.php
@extends('admin.layouts.app')

@section('main')


    <div class="table-responsive">
        <table class="table align-middle mb-0 w-100">
            <thead class="table-light">
            <tr>

                <th class="align-middle">ID</th>
                <th class="align-middle">Bold text</th>
                <th class="align-middle">Top text</th>
                <th class="align-middle">Option 1</th>
                <th class="align-middle">Option 2</th>
                <th class="align-middle">Option 3</th>
                <th class="align-middle">Name</th>
                <th class="align-middle">Phone</th>
                <th class="align-middle">Email</th>
                <th class="align-middle">Interested</th>
                <th class="align-middle">Chek text</th>
                <th class="align-middle">Action</th>
            </tr>
            </thead>
            <tbody>

            @foreach($call_me as $item)
                <tr>
                    <td>{{$item->id}}</td>
                    <td>{{$item->bold_text}}</td>
                    <td>{{$item->top_text}}</td>
                    <td>{{$item->option_1}}</td>
                    <td>{{$item->option_2}}</td>
                    <td>{{$item->option_3}}</td>
                    <td>{{$item->name}}</td>
                    <td>{{$item->phone}}</td>
                    <td>{{$item->email}}</td>
                    <td>{{$item->interested}}</td>
                    <td>{{$item->chek_text}}</td>
                    <td>
                        <form action="{{route('call_me.destroy',$item->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger p-1"><i class="dripicons-trash"></i></button>
                        </form>

                    </td>

                </tr>
            @endforeach


            </tbody>
        </table>
    </div>

@endsection


@section('create')


    <!-- Transaction Modal -->
    <div class="modal fade transaction-detailModal" tabindex="-1" role="dialog" aria-labelledby="transaction-detailModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="transaction-detailModalLabel">Malumotlar qo'shish</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <form action="{{route('call_me.store')}}" method="post">
                    @csrf
                    <div class="modal-body">

                        <label>Bold text</label>
                        <input type="text" name="bold_text" placeholder="Bold text" class="form-control" required>
                        <label>Top text</label>
                        <input type="text" name="top_text" placeholder="Top text" class="form-control" required>
                        <label>Option 1</label>
                        <input type="text" name="option_1" placeholder="Option1" class="form-control" required>
                        <label>Option 2</label>
                        <input type="text" name="option_2" placeholder="Option 2" class="form-control" required>
                        <label>Option 3</label>
                        <input type="text" name="option_3" placeholder="Option 3" class="form-control" required>
                        <label>Name</label>
                        <input type="text" name="name" placeholder="Name" class="form-control" required>
                        <label>Phone</label>
                        <input type="number" name="phone" placeholder="Phone" class="form-control" required>
                        <label>Email</label>
                        <input type="text" name="email" placeholder="Email" class="form-control" required>
                        <label>Interested</label>
                        <input type="text" name="interested" placeholder="Interested" class="form-control" required>
                        <label>Chek text</label>
                        <input type="text" name="chek_text" placeholder="Chek_text" class="form-control" required>


                    </div>


                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end modal -->


@endsection