routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('main',function (){
   return view('main.index');
});

Route::resource('about',\App\Http\Controllers\AboutController::class);

Route::resource('analysis',\App\Http\Controllers\AnalysisController::class);

Route::resource('call_me',\App\Http\Controllers\Call_meController::class);

Route::resource('contacts',\App\Http\Controllers\ContactsController::class);

Route::resource('customers',\App\Http\Controllers\CustomersController::class);

Route::resource('help_business',\App\Http\Controllers\Help_BusinessController::class);

Route::resource('home',\App\Http\Controllers\HomeController::class);

Route::resource('intro',\App\Http\Controllers\IntroController::class);

Route::resource('services',\App\Http\Controllers\ServicesController::class);

Route::resource('teams',\App\Http\Controllers\TeamsController::class);

app/Models/Intro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Intro extends Model
{
    use HasFactory;
    protected $table='intro';
    protected $fillable=['bold_text','top_text','name_text','image'];
    public $timestamps=false;

}

app/Http/Controllers/IntroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Intro;
use Illuminate\Http\Request;

class IntroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $intro=Intro::all();
        return view('admin.intro.index',compact('intro'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'bold_text'=>'required',
            'top_text'=>'required',

            'name_text'=>'required',
            'image'=>'required'
        ]);

        Intro::create([
            'bold_text'=>$request->bold_text,
            'top_text'=>$request->top_text,
            'name_text'=>$request->name_text,

            'image'=>$request->image
        ]);

        return redirect()->route('intro.index');



    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $intro=Intro::find($id);
        $intro->delete();
        return redirect()->route('intro.index');
    }
}

resources/views/admin/intro/index.blade.php
@extends('admin.layouts.app')

@section('main')
    <div class="table-responsive">
        <table class="table align-middle mb-0 w-100">
            <thead class="table-light">
            <tr>

                <th class="align-middle">ID</th>
                <th class="align-middle">Bold text</th>
                <th class="align-middle">Top text </th>
                <th class="align-middle">Name text </th>
                <th class="align-middle">Image</th>
                <th class="align-middle">Action</th>
            </tr>
            </thead>
            <tbody>

            @foreach($intro as $item)
                <tr>
                    <td>{{$item->id}}</td>
                    <td>{{$item->bold_text}}</td>
                    <td>{{$item->top_text}}</td>
                    <td>{{$item->name_text}}</td>
                    <td>{{$item->image}}</td>
                    <td>
                        <form action="{{route('intro.destroy',$item->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger p-1"><i class="dripicons-trash"></i></button>
                        </form>

                    </td>
                </tr>
            @endforeach


            </tbody>
        </table>
    </div>
    <!-- end table-responsive -->
@endsection



@section('create')


    <!-- Transaction Modal -->
    <div class="modal fade transaction-detailModal" tabindex="-1" role="dialog" aria-labelledby="transaction-detailModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="transaction-detailModalLabel">Malumotlar qo'shish</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <form action="{{route('intro.store')}}" method="post">
                    @csrf
                    <div class="modal-body">

                        <label>Bold text</label>
                        <input type="text" name="bold_text" placeholder="Bold text" class="form-control" required>

                        <label>Top text</label>
                        <input type="text" name="top_text" placeholder="Top text" class="form-control" required>



                        <label>Name text</label>
                        <input type="text" name="name_text" placeholder="Name text" class="form-control" required>

                        <label>Image</label>
                        <input type="text" name="image" placeholder="Image" class="form-control" required>

                    </div>


                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end modal -->


@endsection