routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('main',function (){
   return view('main.index');
});

Route::resource('about',\App\Http\Controllers\AboutController::class);

Route::resource('analysis',\App\Http\Controllers\AnalysisController::class);

Route::resource('call_me',\App\Http\Controllers\Call_meController::class);

Route::resource('contacts',\App\Http\Controllers\ContactsController::class);

Route::resource('customers',\App\Http\Controllers\CustomersController::class);

Route::resource('help_business',\App\Http\Controllers\Help_BusinessController::class);

Route::resource('home',\App\Http\Controllers\HomeController::class);

Route::resource('intro',\App\Http\Controllers\IntroController::class);

Route::resource('services',\App\Http\Controllers\ServicesController::class);

Route::resource('teams',\App\Http\Controllers\TeamsController::class);

app/Models/Analysis.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Analysis extends Model
{
    use HasFactory;
    protected $table='analysis';
    protected $fillable=['bold_text','top_text','image'];
    public $timestamps=false;
}

app/Http/Controllers/AnalysisController.php
<?php

namespace App\Http\Controllers;

use App\Models\Analysis;
use Illuminate\Http\Request;

class AnalysisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $analysis=Analysis::all();
        return view('admin.analysis.index',compact('analysis'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'bold_text'=>'required',
            'top_text'=>'required',

            'image'=>'required'

        ]);

        Analysis::create([
            'bold_text'=>$request->bold_text,
            'top_text'=>$request->top_text,

            'image'=>$request->image

        ]);



        return redirect()->route('analysis.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'bold_text'=>'required',
            'top_text'=>'required',

            'image'=>'required'

        ]);

        $analysis=Analysis::find($id);
        $analysis->bold_text=$request->bold_text;
        $analysis->top_text=$request->top_text;
        $analysis-> image=$request->image;
        $analysis->update();




        return redirect()->route('analysis.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $analysis=Analysis::find($id);
        $analysis->delete();
        return redirect()->route('analysis.index');
    }
}

resources/views/admin/analysis/index.blade.php
@extends('admin.layouts.app')
@section('main')

    <div class="table-responsive">
        <table class="table align-middle mb-0 w-100">
            <thead class="table-light">
            <tr>

                <th class="align-middle">ID</th>
                <th class="align-middle">Bold text</th>
                <th class="align-middle">Top text</th>
                <th class="align-middle">Image</th>
                <th class="align-middle">Action</th>

            </tr>
            </thead>
            <tbody>

            @foreach($analysis as $item)
                <tr>
                    <td>{{$item->id}}</td>
                    <td>{{$item->bold_text}}</td>
                    <td>{{$item->top_text}}</td>
                    <td>{{$item->image}}</td>
                    <td class="d-inline-flex">
                        <form action="{{route('analysis.destroy',$item->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger p-1"><i class="dripicons-trash"></i></button>
                        </form>

                        <button type="button" class="p-2 btn btn-success  waves-effect waves-light ms-3 mb-3 bx bxs-edit" data-bs-toggle="modal" data-bs-target="#update{{$item->id}}">

                        </button>


                        <!-- Transaction Modal -->
                        <div id="update{{$item->id}}" class="modal fade transaction-detailModal" tabindex="-1" role="dialog" aria-labelledby="transaction-detailModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="transaction-detailModalLabel">Malumotlar qo'shish</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>

                                    <form action="{{route('analysis.update',$item->id)}}" method="post">
                                        @csrf
                                        @method('PUT')
                                        <div class="modal-body">

                                            <label>Bold text</label>
                                            <input type="text" name="bold_text" placeholder="Bold text" class="form-control" required value="{{$item->bold_text}}">
                                            <label>Top text</label>
                                            <input type="text" name="top_text" placeholder="Top text" class="form-control" required value="{{$item->top_text}}">
                                            <label>Image</label>
                                            <input type="text" name="image" placeholder="Image" class="form-control" required value="{{$item->image}}">

                                        </div>


                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- end modal -->


                    </td>

                </tr>
            @endforeach


            </tbody>
        </table>
    </div>

@endsection


@section('create')


    <!-- Transaction Modal -->
    <div class="modal fade transaction-detailModal" tabindex="-1" role="dialog" aria-labelledby="transaction-detailModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="transaction-detailModalLabel">Malumotlar qo'shish</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <form action="{{route('analysis.store')}}" method="post">
                    @csrf
                    <div class="modal-body">

                        <label>Bold text</label>
                        <input type="text" name="bold_text" placeholder="Bold text" class="form-control" required>
                        <label>Top text</label>
                        <input type="text" name="top_text" placeholder="Top text" class="form-control" required>
                        <label>Image</label>
                        <input type="text" name="image" placeholder="Image" class="form-control" required>

                    </div>


                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end modal -->


@endsection